# Utilisez l'image officielle de MariaDB comme base
FROM mariadb:10.5

# Configuration de la base de données
ENV MYSQL_DATABASE=dockertest \
       MYSQL_USER=root \
       MYSQL_ROOT_PASSWORD=root_password

# Exposez le port 3306
EXPOSE 3306
