#FROM php:8.2-apache
#
#RUN a2enmod rewrite
#
## Install composer
#COPY --from=composer:2.5 /usr/bin/composer /usr/local/bin/composer
#RUN a2enconf my-httpd \
#  && service apache2 restart
#
#CMD ["apache2-foreground"]


FROM php:8.2-apache

RUN a2enmod rewrite

RUN apt-get upgrade -y && apt-get update && apt-get install -y unzip nano tree

RUN  apt-get update \
&& apt-get install -y wget \
&& rm -rf /var/lib/apt/lists/*

COPY ./my-httpd.conf /etc/apache2/conf-available/

RUN a2enconf my-httpd \
  && service apache2 restart

# PHP Librairies
COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/

RUN install-php-extensions bcmath
RUN install-php-extensions intl
RUN install-php-extensions opcache
RUN install-php-extensions xdebug pdo pdo_mysql

# Install composer
#COPY --from=composer:2.5 /usr/bin/composer /usr/local/bin/composer

# Add application files
#ADD . /var/www/html

WORKDIR /var/www/html